#!/usr/bin/env bash

## Applies the ios patch to GHC

set -e

SCRIPT_DIR="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
source "${SCRIPT_DIR}/ghc.env"

pushd "${GHC_BUILD_SRC_DIR}"
patch -p0 -b -z.og < "${GHC_PATCH_PATH}"
