#!/usr/bin/env bash

## This scripts downloads the GHC source

set -e

SCRIPT_DIR="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
source "${SCRIPT_DIR}/ghc.env"

mkdir -p "${BUILD_DIR}"
wget -c "${GHC_SRC_URL}" -O "${GHC_BUILD_SRCTAR_PATH}"

